#!/bin/bash
set -ex

docker-compose down
../exe/kumonos envoy -o config.json ../example/envoy_config.yml
rm -rf srv
mkdir srv
../exe/kumonos clusters -o srv ../example/book.yml
../exe/kumonos routes -o srv ../example/book.yml
docker-compose up --build -d
ruby test.rb
docker-compose down
